### ISSUE TITLE
LRT with different minimizers per model

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#180]
I am attempting to the run LRT on two models where I have used two different minimizers but the LRT selects the minimizer of the jl_0 to fit simulations of jl_1, which, in my case, is a GRID minimizer with specific parameters. Should we modify the LRT to use the correct minimizer?

**Comment by giacomov** [comment]
Does it really make a difference? The fit will start from the best fit values already stored in the JointLikelihood objects, so it shouldn't be necessary to do the grid fitting again (which is super slow)...

**Comment by grburgess** [comment]
True. But, it causes the fit to fail because it invokes the grid minimizer which is looking for model parameters that do not exist. One could change the minimizer of course, but it could confuse people. Get what I am saying?

**Comment by giacomov** [comment]
Look at the code [here](https://github.com/giacomov/3ML/blob/d02e899526d6c94f2b752cf47e4ddfec6858cad7/threeML/classicMLE/likelihood_ratio_test.py#L109-L113): as you can see, I am using the feature of the JointLikelihoodSet object which is able to fit more than one model at the time. This implies that it will use the same minimizer for both models. 

I am going to add a set_minimizer method to the LikelihoodRatioTest object that override that. If you don't use, LRT will try using the minimizer from the first JointLikelihood object, otherwise it will use the provided one. Would that work?

**Comment by grburgess** [comment]
I think that will work fine. I can always switch myself, but this will make it explicit.
