### ISSUE TITLE
Fortran issue for mac when installing 3ML

### ISSUE THREAD

**Issue by sptfung** [giacomov/3ML#216]
Hi,

I had my fortran installed via Homebrew gcc and followed the tips in the 3ML installation page to export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/:$DYLD_LIBRARY_PATH

however I still get 
```
    IOError: Could not find library gfortran. Impossible to compile Xspec
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kd/ds_cprnn6r39bwt0zgv832_w0000gn/T/pip-build-VUHXZA/astromodels/
```

and unsuccessful in installing 3ML. I am wondering is this a stupid question?

Thanks,
David

**Comment by giacomov** [comment]
Hi David,
there is no stupid question :-) (more or less)

Where is your libgfortran*.dylib in your mac? 

Keep in mind that 3ML installs the Xspec model part only if you have a HEADAS variable when you run the installation. If you have that variable, make sure that Xspec is actually working before trying to install 3ML. If XSpec is not working, then the 3ML installation will fail because of that.

FYI: I am working on a Anaconda installation for 3ML. I am still testing it, but if you want to check that out, install miniconda then just issue `conda install threeml` and everything will be done (also XSpec models). If then you want to develop for 3ML, you can still do so by checking out the code from the github repository.

**Comment by sptfung** [comment]
Hi Giacomo,

Thanks for the answer. My libgfortran*.dylib are in /usr/local/lib/gcc/7/ and I have checked that XSPEC is working before doing pip install git+https://github.com/giacomov/3ML.git, my $DYLD_LIBRARY_PATH reads
`/usr/local/lib/gcc/:/Users/hfyu/heasoft-6.21/x86_64-apple-darwin16.5.0/lib`

I also tried to install the virtual env 3ML but the same problem persists.

I will try your miniconda method!

David

**Comment by giacomov** [comment]
You should then use /usr/local/lib/gcc/7 in your DYLD_LIBRARY_PATH . Try changing that and see if that fixes it.

**Comment by sptfung** [comment]
Hi Giacomo,

Thanks, it is fixed after /7/ is added, so it shows that my question is really stupid because I thought it applies to sub-directories...

The 3ML_env seems to encounter another problem with matplotlib
`RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.`

It seems to be a known issue: http://matplotlib.org/faq/virtualenv_faq.html
but I did not test it.

Thanks,
David

**Comment by grburgess** [comment]
I just noticed homebrew changed the path to include the version number. I'll update the instructions.
