### ISSUE TITLE
XYLike NaN in chi2

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#244]
In the chi2 calculation in XYLike, there is an assertion to make sure that chi2 is finite. This makes sense, however, this can happen when functions overflow. When running sampling methods, this can cause an iteration to crash the kernel (emcee) or append nonsense to MUTINEST chains when a parameter wanders into a poorly defined function region. 

Should we instead try to numpy.nan_to_number the output or deal generally with overflows in the Functions base?

**Comment by giacomov** [comment]
do you know when does the NaN comes from in the chi2 formula? Does it come from the model part?

In general I think it is dangerous to "cover" problems by silently ignoring them. 

In a Bayesian context you should probably put priors excluding the region that give you nans. That being said, one thing we could do would be to issue a warning instead of an AssertionError when the NaN happens. However, given the parallel nature of things like Multinest, the user might never see the warning depending on where it happens...

Regarding the overflow, I find it difficult to believe that you want to keep a situation where a float does not fit into the range 10^(-308) - 10^(308) (on modern computer, this is the range of double precision floating point numbers)...

**Comment by grburgess** [comment]
I agree with all of the above. I'm working on diagnosing the problem. I just noticed that we do not do this in other plugins and I haven't had the same problems. 

It is possible that this issue is popping up in XSPEC models (which I am using) or the complex likelihood I'm using a.t.m. 

But, some of the functions (things involving exponentials) overflow very commonly when used outside of the typical x-ray energy range, so priors aren't going to help. 

I'll investigate further. Just wanted your opinion on that line of code. Perhaps we should put in the other plugins as well.

**Comment by grburgess** [comment]
Indeed, it's when a function creates zero flux and you want to calculate a magnitude. The log throws infinite. You can't really patch this up because making the magnitude very large 1e308 causes a division error in the chi2. I propose we just set it to an arbitrarily large magnitude which should penalize the likelihood enough to put pressure away from that point. I'm sure there are statistical problema that arise from this... But I see no other way
