### ISSUE TITLE
pip install issue: execfile

### ISSUE THREAD

**Issue by JohannesBuchner** [giacomov/3ML#279]
This is on python 3.5:
```
$ pip install threeml --user
Collecting threeml
  Downloading threeML-0.3.2.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 184kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0bcwqy3j/threeml/setup.py", line 9, in <module>
        execfile('threeML/version.py')
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0bcwqy3j/threeml/

```

Potentially useful links:
https://github.com/bulkan/robotframework-requests/issues/109
https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by giacomov** [comment]
I just commited a fix. However, keep in mind that there are other places where 3ML is not compatible with python 3. We are in the process of 2 -> 3. Of course, if you want to contribute to that, you're very welcome.
 We need to keep compatibility with python 2 as well, because some of the plugins (most notably Fermi/LAT) needs it still.
