### ISSUE TITLE
Use panda for results

### ISSUE THREAD

**Issue by giacomov** [giacomov/3ML#44]
Using panda containers for results would make things much easier when performing time-resolved fitting or many fit one after the other. 

Panda containers can be appended, merged, provide rich display functionalities and saved to disk.

**Comment by drJfunk** [comment]
I agree. Pandas is very nice and contains all the ability to save to the disk. The question I have is should you make it so that when you load a pandas result, do you want it to contain all the info? (detectors used  etc.) It would probably make more sense to just use the notebook for this. However, if one is doing catalogs, then have all this in a file that can easily be turned into LaTeX would be very nice.

**Comment by giacomov** [comment]
I think the saving of the model and of the data should be separate, because the former can be used and read by other software, while the latter cannot (you need to use 3ML and have the same plugins installed).

However, all the plugins should be already pickeable, so we could easily provide a save_data(dataList) method which would save all the instances of the plugins in pickle (or dill) format so they can be reloaded from disk (and you don't even need the original data for this).
