### ISSUE TITLE
Plotting of spectra

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#45]
We need a routine that is either attached to the model via atromodels or can read a model object and plot the results in a nice form.

I suggest that we do this via the model object in 3ML since it is data aware. I can work on this unless @giacomov has an idea.

**Comment by giacomov** [comment]
I agree that the place for plotting routine is in 3ML, not astromodels. Astromodels does not depend on matplotlib nor any other plotting package and it would be better to keep it that way (although an optional dependence could be accomodated).

The Model object is in astromodels, so that's probably not the right place for the reason above.

Also, what do you mean by plotting of spectra? You mean just the model, or the model plus data?

For the latter, some (most) of the plugins have a .display() method which plots the spectrum and the model (and residuals) for that plugin. You could start by adding it do plugins who don't have it yet.

We need to think this through for the rest, because differently from Xspec, Rmfit and the like, models here can have more than one source, and sources can be point-like, extended or even particle sources.

Also, not all plugins will have the same data coordinates. For example, HAWC doesn't have energy Vs flux, but nHit Vs flux. Some of the instruments have imaging capabilities, some don't. So some plugins will need to implement a .display() capable of making images as well.

So probably a global plot with all data is not easy to achieve.

One way to go would be:

1. For plotting the model itself (without the data) we can provide a global function which can plot one or multiple sources in the same plot, or the sum of all of them. If there are samples from MCMC the function should compute the "error region" by taking the percentiles. So it would be something like:

> plot_model(analysis, x_unit='keV', y_unit='erg / (cm2 s)', list_of_sources_to_plot=[], percentiles=[0.32,0.84], sum=True)

where analysis can be either a JointLikelihood or a BayesianAnalysis object. 
So plot_model(jl) would plot the nuFnu of all sources with different colors, plot_model(jl, [source_1, source_5]) would only plot source 1 and 5, plot_model(jl, sum=True) would plot the sum of all the spectra, plot_model(jl, y_unit='1 / (cm2 s)') would plot the photon flux, plot_model(jl, x_unit='Hz') would plot the spectrum in frequency and so on. The same but using a BayesianAnalysis object would also produce the shaded "error regions" (using fill_between).

2. For plotting the data, we should make sure that every plugin implements a .display() method, which can tailor the plot to the data of the instrument.

**Comment by drJfunk** [comment]
Exactly! But we should also plot contours for the JL objects by propagating the covariance matrix. I have a general method for this that is model agnostic.

We should enforce no plotting pseudo-model data points as this is non-sense. 

I'll take a look at this. If you like, I will take it on.

**Comment by giacomov** [comment]
Go for it!

Leave the covariance matrix part alone for the moment, I implemented a lot more minimizers than just minuit and had to change the API of the minimizer a bit. I am testing them, will commit next week.

-----Original Message-----

**Comment by drJfunk** [comment]
added with #50
