### ISSUE TITLE
Priors for nuisance parameters

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#74]
I noticed in OGIPLike that the an uninformative flat prior was being used for the effective area correction.

I would suggest instead that we use a gaussian or even better, a cauchy prior for these:

1) we believe they should be centered on zero, so we have some information there.
2) while we would preferably set the variance of the distribution as a free parameter, we aren't going to do any fancy modeling here... so we can set a cauchy prior, centered at zero with beta=2.5

This is slightly less informative around the center than a gaussian but still uses our knowledge that we should not have something too far off in the tails. 2.5 comes from some work by Gelman that says this is uninformative around the mean. 

There are not Cauchy priors in astro models... but maybe there should be :)

**Comment by giacomov** [comment]
Hi,
1) they should be centered on 1, not on zero
2) this is interesting, however I'd prefer to keep the obvious choice of uniform priors. The only reason there is a "default" prior in the first place is that otherwise the BayesianAnalysis constructor will fail. However, the user can always override the default choice before running the analysis.

Regarding the Cauchy priors, you are definitely welcome to contribute them to the Astromodels repository.

**Comment by drJfunk** [comment]
:) yes=>1 Ok. I'll handle this
